//go:build !ignore_autogenerated

/*
Copyright 2024 liuchong.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronScale) DeepCopyInto(out *CronScale) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronScale.
func (in *CronScale) DeepCopy() *CronScale {
	if in == nil {
		return nil
	}
	out := new(CronScale)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CronScale) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronScaleAdd) DeepCopyInto(out *CronScaleAdd) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronScaleAdd.
func (in *CronScaleAdd) DeepCopy() *CronScaleAdd {
	if in == nil {
		return nil
	}
	out := new(CronScaleAdd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronScaleList) DeepCopyInto(out *CronScaleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CronScale, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronScaleList.
func (in *CronScaleList) DeepCopy() *CronScaleList {
	if in == nil {
		return nil
	}
	out := new(CronScaleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CronScaleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronScaleMinus) DeepCopyInto(out *CronScaleMinus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronScaleMinus.
func (in *CronScaleMinus) DeepCopy() *CronScaleMinus {
	if in == nil {
		return nil
	}
	out := new(CronScaleMinus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronScaleSpec) DeepCopyInto(out *CronScaleSpec) {
	*out = *in
	out.Minus = in.Minus
	out.Add = in.Add
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronScaleSpec.
func (in *CronScaleSpec) DeepCopy() *CronScaleSpec {
	if in == nil {
		return nil
	}
	out := new(CronScaleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronScaleStatus) DeepCopyInto(out *CronScaleStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronScaleStatus.
func (in *CronScaleStatus) DeepCopy() *CronScaleStatus {
	if in == nil {
		return nil
	}
	out := new(CronScaleStatus)
	in.DeepCopyInto(out)
	return out
}
