# permissions for end users to edit cronscales.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cronscale-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cronscale-operator
    app.kubernetes.io/part-of: cronscale-operator
    app.kubernetes.io/managed-by: kustomize
  name: cronscale-editor-role
rules:
- apiGroups:
  - application.liuchong.cn
  resources:
  - cronscales
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.liuchong.cn
  resources:
  - cronscales/status
  verbs:
  - get
